import type { Receipt } from './types';

export const MOCK_RECEIPTS: Receipt[] = [
  {
    id: 'rcpt_001',
    order_number: 'JMP-2026-0654',
    product_name: 'Hand-Carved Ebony Wood Serving Bowl',
    status: 'delivered',
    total_usd: 189.5,
    subtotal_usd: 165.0,
    unit_price_usd: 165.0,
    shipping_usd: 20.0,
    platform_fee_usd: 4.5,
    quantity: 1,
    created_at: '2026-05-15T09:20:00Z',
    listing_photos: ['https://picsum.photos/seed/ebony-bowl/200/200'],
    ships_from: 'Lagos, Nigeria',
    shipping_name: 'Chioma Okonkwo',
    shipping_address: '451 Maple Ave, Apt 3B, Houston, TX 77002',
    escrow_held_by: 'Riby Inc (US Escrow)',
  },
  {
    id: 'rcpt_002',
    order_number: 'JMP-2026-0588',
    product_name: 'Nigerian Spice Rub Collection (4 Jars)',
    status: 'delivered',
    total_usd: 69.99,
    subtotal_usd: 55.0,
    unit_price_usd: 13.75,
    shipping_usd: 12.99,
    platform_fee_usd: 2.0,
    quantity: 4,
    created_at: '2026-04-28T11:00:00Z',
    listing_photos: ['https://picsum.photos/seed/spice-rub/200/200'],
    ships_from: 'Abuja, Nigeria',
    shipping_name: 'Chioma Okonkwo',
    shipping_address: '451 Maple Ave, Apt 3B, Houston, TX 77002',
    escrow_held_by: 'Riby Inc (US Escrow)',
  },
  {
    id: 'rcpt_003',
    order_number: 'JMP-2026-0710',
    product_name: 'Cotton Kaftan – Navy Blue, XL',
    status: 'delivered',
    total_usd: 110.0,
    subtotal_usd: 95.0,
    unit_price_usd: 95.0,
    shipping_usd: 13.0,
    platform_fee_usd: 2.0,
    quantity: 1,
    created_at: '2026-06-05T15:30:00Z',
    listing_photos: ['https://picsum.photos/seed/kaftan/200/200'],
    ships_from: 'Kano, Nigeria',
    shipping_name: 'Chioma Okonkwo',
    shipping_address: '451 Maple Ave, Apt 3B, Houston, TX 77002',
    escrow_held_by: 'Riby Inc (US Escrow)',
  },
  {
    id: 'rcpt_004',
    order_number: 'JMP-2026-0881',
    product_name: 'Beaded Leather Sandals – Size 9',
    status: 'delivered',
    total_usd: 352.77,
    subtotal_usd: 310.0,
    unit_price_usd: 62.0,
    shipping_usd: 35.77,
    platform_fee_usd: 7.0,
    quantity: 5,
    created_at: '2026-06-12T13:00:00Z',
    listing_photos: ['https://picsum.photos/seed/sandals/200/200'],
    ships_from: 'Lagos, Nigeria',
    shipping_name: 'Chioma Okonkwo',
    shipping_address: '451 Maple Ave, Apt 3B, Houston, TX 77002',
    escrow_held_by: 'Riby Inc (US Escrow)',
  },
  {
    id: 'rcpt_005',
    order_number: 'JMP-2026-0399',
    product_name: 'Hand-dyed Ankara Print Fabric (6 Yards)',
    status: 'delivered',
    total_usd: 145.0,
    subtotal_usd: 120.0,
    unit_price_usd: 20.0,
    shipping_usd: 22.0,
    platform_fee_usd: 3.0,
    quantity: 6,
    created_at: '2026-03-20T07:00:00Z',
    listing_photos: ['https://picsum.photos/seed/ankara/200/200'],
    ships_from: 'Lagos, Nigeria',
    shipping_name: 'Chioma Okonkwo',
    shipping_address: '451 Maple Ave, Apt 3B, Houston, TX 77002',
    escrow_held_by: 'Riby Inc (US Escrow)',
  },
];
