import type { PaymentMethod, PaymentKind } from './types';

export const MOCK_PAYMENT_METHODS: PaymentMethod[] = [
  {
    id: 1,
    type: 1,
    provider: null,
    displayName: 'Visa ···· 4242',
    lastFourDigits: '4242',
    expiryMonth: '08',
    expiryYear: '2029',
    isDefault: true,
    zelleEmail: null,
    bankName: null,
    accountNumber: null,
    createdAt: '2025-01-01T00:00:00',
  },
  {
    id: 2,
    type: 1,
    provider: null,
    displayName: 'Mastercard ···· 8881',
    lastFourDigits: '8881',
    expiryMonth: '03',
    expiryYear: '2028',
    isDefault: false,
    zelleEmail: null,
    bankName: null,
    accountNumber: null,
    createdAt: '2025-02-01T00:00:00',
  },
  {
    id: 3,
    type: 2,
    provider: null,
    displayName: 'chioma@email.com',
    lastFourDigits: null,
    expiryMonth: null,
    expiryYear: null,
    isDefault: false,
    zelleEmail: 'chioma@email.com',
    bankName: null,
    accountNumber: null,
    createdAt: '2025-03-01T00:00:00',
  },
  {
    id: 4,
    type: 3,
    provider: null,
    displayName: 'Chase Checking ···· 7732',
    lastFourDigits: '7732',
    expiryMonth: null,
    expiryYear: null,
    isDefault: false,
    zelleEmail: null,
    bankName: 'Chase',
    accountNumber: '****7732',
    createdAt: '2025-04-01T00:00:00',
  },
];

export const PAYMENT_KINDS: { v: PaymentKind; l: string }[] = [
  { v: 'card', l: 'Credit / Debit Card' },
  { v: 'zelle', l: 'Zelle' },
  { v: 'ach', l: 'ACH Bank Transfer' },
];
