import {
  CreditApplicationX,
  CreditEligibility,
  CreditApplication,
  Dispute,
  OverviewType,
  Product,
  Verification,
  VerificationItem,
  Order,
  OrderDetailData,
  OrderStatus,
  Listing,
  SellerQuote,
  FulfillmentOrder,
  WithdrawalAccount,
  NgnBank,
  RepaymentData,
  Business,
} from '../types/exporter';

export const mockOverview: OverviewType = {
  business_count: 128,
  order_count: 542,
  transaction_count: 789,
  fees_collected_usd: 12450,

  total_volume_by_currency: {
    USD: 95000,
    NGN: 42000000,
    EUR: 12000,
  },

  by_sector: {
    fashion: { volume_usd: 32000, count: 120 },
    beauty: { volume_usd: 18000, count: 90 },
    food: { volume_usd: 45000, count: 210 },
    electronics: { volume_usd: 12000, count: 60 },
  },
};

export const mockVerifications: Verification[] = [
  {
    id: 'v1',
    business_name: 'Lagos Textiles Ltd',
    country: 'Nigeria',
    sector: 'beauty',
    kyc_status: 'pending',
    kyb_status: 'pending',
    updated_at: '2026-04-28T10:00:00Z',
  },
  {
    id: 'v2',
    business_name: 'Accra Shea Co.',
    country: 'Ghana',
    sector: 'beauty',
    kyc_status: 'pending',
    kyb_status: 'pending',
    updated_at: '2026-04-29T14:20:00Z',
  },
  {
    id: 'v3',
    business_name: 'Addis Coffee Export',
    country: 'Ethiopia',
    sector: 'food',
    kyc_status: 'approved',
    kyb_status: 'approved',
    updated_at: '2026-04-27T08:15:00Z',
  },
];
export const sampleVerifications: VerificationItem[] = [
  {
    id: 'verif-001',
    business_name: 'Lagos Agro Exports Ltd',
    registration_type: 'LLC',
    country: 'Nigeria',
    sector: 'agriculture',
    anchor_customer_id: 'anchor-88921',
    cac_number: 'RC-1293847',
    bvn: '22345678901',
    tin: 'TIN-99887766',
    director_name: 'Adebayo Ogunleye',
    kyc_status: 'pending',
    kyb_status: 'pending',
  },
  {
    id: 'verif-002',
    business_name: 'Accra Shea Butter Co.',
    registration_type: 'Partnership',
    country: 'Ghana',
    sector: 'beauty',
    bvn: '33445566778',
    director_name: 'Ama Mensah',
    kyc_status: 'approved',
    kyb_status: 'pending',
  },
  {
    id: 'verif-003',
    business_name: 'Nairobi Coffee Exporters',
    registration_type: 'Corporation',
    country: 'Kenya',
    sector: 'food',
    ein: 'EIN-55443322',
    director_name: 'David Mwangi',
    kyc_status: 'approved',
    kyb_status: 'approved',
  },
  {
    id: 'verif-004',
    business_name: 'Cape Textiles Studio',
    registration_type: 'Sole Proprietorship',
    country: 'South Africa',
    sector: 'fashion',
    tin: 'TIN-11223344',
    director_name: 'Thandi Nkosi',
    kyc_status: 'rejected',
    kyb_status: 'rejected',
  },
];
export const creditApplications: CreditApplicationX[] = [
  {
    id: 'app_1',
    application_number: 'JSC-10021',
    business_name: 'Lagos Heritage Textiles Ltd',
    business_country: 'Nigeria',
    amount_usd: 25000,
    indicative_apr: 18,
    term_months: 12,
    risk_score: 72,
    status: 'submitted',
    created_at: '2026-04-20T10:15:00.000Z',
    snapshot_sales: {
      total_volume_usd: 42000,
    },
  },
  {
    id: 'app_2',
    application_number: 'JSC-10022',
    business_name: 'Accra Agro Exporters',
    business_country: 'Ghana',
    amount_usd: 50000,
    indicative_apr: 15,
    term_months: 18,
    risk_score: 61,
    status: 'under_review',
    created_at: '2026-04-18T14:30:00.000Z',
    snapshot_sales: {
      total_volume_usd: 98000,
    },
  },
  {
    id: 'app_3',
    application_number: 'JSC-10023',
    business_name: 'Nairobi Coffee Collective',
    business_country: 'Kenya',
    amount_usd: 120000,
    indicative_apr: 12,
    term_months: 24,
    risk_score: 45,
    status: 'offered',
    created_at: '2026-04-15T09:00:00.000Z',
    snapshot_sales: {
      total_volume_usd: 210000,
    },
  },
  {
    id: 'app_4',
    application_number: 'JSC-10024',
    business_name: 'Abuja Food Distributors',
    business_country: 'Nigeria',
    amount_usd: 15000,
    indicative_apr: 22,
    term_months: 6,
    risk_score: 81,
    status: 'rejected',
    created_at: '2026-04-10T08:45:00.000Z',
    snapshot_sales: {
      total_volume_usd: 18000,
    },
  },
];
export const disputes: Dispute[] = [
  {
    id: 'disp_1',
    reason: 'Item not received',
    order_id: 'ORD-77821',
    description:
      'Buyer claims package was marked delivered but never received the shipment.',
    status: 'open',
    created_at: '2026-04-25T12:30:00.000Z',
  },
  {
    id: 'disp_2',
    reason: 'Product not as described',
    order_id: 'ORD-77822',
    description:
      'Customer received different fabric quality compared to listing photos.',
    status: 'under_review',
    created_at: '2026-04-26T09:10:00.000Z',
  },
];
export const products: Product[] = [
  {
    id: '3b58c1c6-164c-407c-906a-c940fcc3ce75',
    business_id: '19e8e37e-a736-42d0-a2ee-f4c07108ea5f',
    name: 'Leather Tote — Handcrafted (Lagos Edition)',
    category: 'fashion',
    description:
      'Full-grain Nigerian leather tote bag, hand-stitched in Lagos. Individually numbered, with origin certificate.',
    photos: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80',
    ],
    price_ngn: 161802.35,
    price_usd: 120.0,
    min_order_qty: 10,
    unit: 'piece',
    export_readiness_score: 70,
    compliance_badges: ['Country-of-Origin Label'],
    status: 'active',
    created_at: '2026-04-22T04:43:07.669023Z',
  },
  {
    id: 'c1a7e5b2-9914-4f3c-8a9d-1d7d3d8caa21',
    business_id: '19e8e37e-a736-42d0-a2ee-f4c07108ea5f',
    name: 'Adire Indigo Fabric Roll',
    category: 'textiles',
    description:
      'Traditional hand-dyed Adire fabric from Abeokuta artisans. Sold in bulk rolls for export markets.',
    photos: [
      'https://images.unsplash.com/photo-1528459105426-b9548367069b?auto=format&fit=crop&w=900&q=80',
    ],
    price_ngn: 95000,
    price_usd: 70,
    min_order_qty: 20,
    unit: 'roll',
    export_readiness_score: 82,
    compliance_badges: ['Eco Dye Certified', 'Country-of-Origin Label'],
    status: 'active',
    created_at: '2026-04-20T08:12:10.000Z',
  },
  {
    id: '7d2f4b0c-5c77-4f0d-9c21-6a32c44b0b12',
    business_id: '19e8e37e-a736-42d0-a2ee-f4c07108ea5f',
    name: 'Shea Butter — Premium Grade (Organic)',
    category: 'beauty',
    description:
      'Raw unrefined shea butter sourced from Northern Nigeria, processed using traditional methods.',
    photos: [
      'https://images.unsplash.com/photo-1590086782792-42dd2350140d?auto=format&fit=crop&w=900&q=80',
    ],
    price_ngn: 35000,
    price_usd: 25,
    min_order_qty: 50,
    unit: 'kg',
    export_readiness_score: 88,
    compliance_badges: ['Organic Certified', 'FDA Export Ready'],
    status: 'active',
    created_at: '2026-04-18T10:30:00.000Z',
  },
  {
    id: 'a8b9d1e2-2f4b-4e1a-9a5c-33c4b2f6d981',
    business_id: '19e8e37e-a736-42d0-a2ee-f4c07108ea5f',
    name: 'Dried Hibiscus (Zobo) Export Pack',
    category: 'agro',
    description:
      'Sun-dried hibiscus petals packaged for international markets. High-grade export quality.',
    photos: [
      'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=900&q=80',
    ],
    price_ngn: 42000,
    price_usd: 32,
    min_order_qty: 30,
    unit: 'bag',
    export_readiness_score: 90,
    compliance_badges: ['NAFDAC Approved', 'Phytosanitary Certified'],
    status: 'active',
    created_at: '2026-04-17T14:45:00.000Z',
  },
  {
    id: 'f4c3e2b1-6d77-4a88-bb1d-55c9d3f2a111',
    business_id: '19e8e37e-a736-42d0-a2ee-f4c07108ea5f',
    name: 'Hand-Carved Wooden Bowl Set',
    category: 'crafts',
    description:
      'Set of handcrafted wooden bowls made from sustainable Nigerian hardwood. Export-grade finishing.',
    photos: [
      'https://images.unsplash.com/photo-1616627456059-0c4cfd4a0e8b?auto=format&fit=crop&w=900&q=80',
    ],
    price_ngn: 78000,
    price_usd: 58,
    min_order_qty: 15,
    unit: 'set',
    export_readiness_score: 76,
    compliance_badges: ['Sustainably Sourced'],
    status: 'active',
    created_at: '2026-04-15T09:20:00.000Z',
  },
];

//orders

export const orders: Order[] = [
  {
    id: 'ord-a1b2c3d4-0001',
    order_number: 'ORD-0041',
    buyer_user_id: 'usr-buyer-001',
    product_name: 'Premium Sesame Seeds (50kg bags)',
    quantity: 200,
    agreed_price_usd: 3200,
    target_delivery_date: '2026-06-15',
    status: 'in_progress',
    payment_status: 'paid',
  },
  {
    id: 'ord-a1b2c3d4-0002',
    order_number: 'ORD-0039',
    buyer_user_id: 'usr-buyer-002',
    product_name: 'Refined Shea Butter — Grade A',
    quantity: 80,
    agreed_price_usd: 1600,
    target_delivery_date: '2026-06-20',
    status: 'pending',
    payment_status: 'awaiting',
  },
  {
    id: 'ord-a1b2c3d4-0003',
    order_number: 'ORD-0035',
    buyer_user_id: 'usr-buyer-001',
    product_name: 'Hibiscus Flower (Dried, Export Grade)',
    quantity: 500,
    agreed_price_usd: 5500,
    target_delivery_date: '2026-05-30',
    status: 'completed' as OrderStatus,
    payment_status: 'paid',
  },
  {
    id: 'ord-a1b2c3d4-0004',
    order_number: 'ORD-0033',
    buyer_user_id: 'usr-buyer-003',
    product_name: 'Fermented Cocoa Beans (Fine Flavour)',
    quantity: 1000,
    agreed_price_usd: 42000,
    target_delivery_date: '2026-07-01',
    status: 'confirmed',
    payment_status: 'paid',
  },
  {
    id: 'ord-a1b2c3d4-0005',
    order_number: 'ORD-0031',
    buyer_user_id: 'usr-buyer-002',
    product_name: 'Adire Indigo Fabric Roll',
    quantity: 40,
    agreed_price_usd: 2800,
    target_delivery_date: '2026-06-10',
    status: 'in_progress',
    payment_status: 'paid',
  },
  {
    id: 'ord-a1b2c3d4-0006',
    order_number: 'ORD-0028',
    buyer_user_id: 'usr-buyer-001',
    product_name: 'Raw Cashew Nuts — W240 Grade',
    quantity: 500,
    agreed_price_usd: 19000,
    target_delivery_date: '2026-05-25',
    status: 'completed' as OrderStatus,
    payment_status: 'paid',
  },
  {
    id: 'ord-a1b2c3d4-0007',
    order_number: 'ORD-0025',
    buyer_user_id: 'usr-buyer-004',
    product_name: 'Moringa Leaf Powder — Organic Certified',
    quantity: 100,
    agreed_price_usd: 4500,
    target_delivery_date: '2026-07-15',
    status: 'pending',
    payment_status: 'awaiting',
  },
  {
    id: 'ord-a1b2c3d4-0008',
    order_number: 'ORD-0022',
    buyer_user_id: 'usr-buyer-003',
    product_name: 'Black Soap (Dudu Osun) — Bulk Export',
    quantity: 300,
    agreed_price_usd: 4200,
    target_delivery_date: '2026-06-05',
    status: 'cancelled',
    payment_status: 'refunded',
  },
  {
    id: 'ord-a1b2c3d4-0009',
    order_number: 'ORD-0019',
    buyer_user_id: 'usr-buyer-002',
    product_name: 'Long-Grain Parboiled Rice (25kg sacks)',
    quantity: 600,
    agreed_price_usd: 14400,
    target_delivery_date: '2026-06-28',
    status: 'confirmed',
    payment_status: 'paid',
  },
  {
    id: 'ord-a1b2c3d4-0010',
    order_number: 'ORD-0015',
    buyer_user_id: 'usr-buyer-001',
    product_name: 'Leather Tote — Handcrafted (Lagos Edition)',
    quantity: 25,
    agreed_price_usd: 3000,
    target_delivery_date: '2026-07-20',
    status: 'in_progress',
    payment_status: 'paid',
  },
  {
    id: 'ord-a1b2c3d4-0011',
    order_number: 'ORD-0012',
    buyer_user_id: 'usr-buyer-004',
    product_name: 'Dried Hibiscus (Zobo) Export Pack',
    quantity: 60,
    agreed_price_usd: 1920,
    target_delivery_date: '2026-05-20',
    status: 'completed' as OrderStatus,
    payment_status: 'paid',
  },
  {
    id: 'ord-a1b2c3d4-0012',
    order_number: 'ORD-0009',
    buyer_user_id: 'usr-buyer-003',
    product_name: 'Hand-Carved Wooden Bowl Set',
    quantity: 30,
    agreed_price_usd: 1740,
    target_delivery_date: '2026-08-01',
    status: 'pending',
    payment_status: 'awaiting',
  },
  {
    id: 'ord-a1b2c3d4-0013',
    order_number: 'ORD-0006',
    buyer_user_id: 'usr-buyer-001',
    product_name: 'Yellow Plantain Flour — Fine Milled',
    quantity: 200,
    agreed_price_usd: 3600,
    target_delivery_date: '2026-06-12',
    status: 'completed' as OrderStatus,
    payment_status: 'paid',
  },
  {
    id: 'ord-a1b2c3d4-0014',
    order_number: 'ORD-0004',
    buyer_user_id: 'usr-buyer-002',
    product_name: 'Handwoven Kente Cloth — Gold & Black',
    quantity: 20,
    agreed_price_usd: 1700,
    target_delivery_date: '2026-07-08',
    status: 'in_progress',
    payment_status: 'paid',
  },
  {
    id: 'ord-a1b2c3d4-0015',
    order_number: 'ORD-0002',
    buyer_user_id: 'usr-buyer-004',
    product_name: 'Smoked Tuna Fillets — Vacuum Packed',
    quantity: 80,
    agreed_price_usd: 2560,
    target_delivery_date: '2026-06-30',
    status: 'confirmed',
    payment_status: 'awaiting',
  },
];

// Order Details

export const mockOrderDetails: Record<string, OrderDetailData> = {
  'ord-a1b2c3d4-0001': {
    order: {
      id: 'ord-a1b2c3d4-0001',
      order_number: 'ORD-0041',
      buyer_user_id: 'usr-buyer-001',
      supplier_user_id: 'usr-supplier-001',
      product_name: 'Premium Sesame Seeds (50kg bags)',
      quantity: 200,
      agreed_price_usd: 3200,
      unit_price_usd: 16,
      target_delivery_date: '2026-06-15',
      delivery_address: '12 Marina Road, Lagos Island, Lagos, Nigeria',
      status: 'in_progress',
      payment_status: 'paid',
      anchor_reserved_account_number: 'ANC-9900012345',
      timeline: [
        { event: 'status:in_progress', at: '2026-04-25T10:00:00Z' },
        { event: 'payment_confirmed', at: '2026-04-23T08:30:00Z' },
        { event: 'proforma_issued', at: '2026-04-22T14:10:00Z' },
        { event: 'status:confirmed', at: '2026-04-21T09:00:00Z' },
        { event: 'rfq_submitted', at: '2026-04-20T11:45:00Z' },
      ],
    },
    supplier: { business_name: 'NorthGrain Agro Exports', country: 'Nigeria' },
    buyer: { business_name: 'Global Foods Import GmbH', country: 'Germany' },
  },
  'ord-a1b2c3d4-0002': {
    order: {
      id: 'ord-a1b2c3d4-0002',
      order_number: 'ORD-0039',
      buyer_user_id: 'usr-buyer-002',
      supplier_user_id: 'usr-supplier-001',
      product_name: 'Refined Shea Butter — Grade A',
      quantity: 80,
      agreed_price_usd: 1600,
      unit_price_usd: 20,
      target_delivery_date: '2026-06-20',
      delivery_address: '88 Kingsway Avenue, London, UK',
      status: 'pending',
      payment_status: 'awaiting',
      anchor_reserved_account_number: 'ANC-9900054321',
      timeline: [{ event: 'rfq_submitted', at: '2026-04-28T13:00:00Z' }],
    },
    supplier: {
      business_name: 'Savannah Naturals Export Co.',
      country: 'Nigeria',
    },
    buyer: {
      business_name: 'Pure Beauty Imports Ltd',
      country: 'United Kingdom',
    },
  },
  'ord-a1b2c3d4-0003': {
    order: {
      id: 'ord-a1b2c3d4-0003',
      order_number: 'ORD-0035',
      buyer_user_id: 'usr-buyer-001',
      supplier_user_id: 'usr-supplier-002',
      product_name: 'Hibiscus Flower (Dried, Export Grade)',
      quantity: 500,
      agreed_price_usd: 5500,
      unit_price_usd: 11,
      target_delivery_date: '2026-05-30',
      delivery_address: '5 Rue du Commerce, Paris, France',
      status: 'delivered',
      payment_status: 'paid',
      anchor_reserved_account_number: null,
      timeline: [
        { event: 'status:delivered', at: '2026-05-28T16:00:00Z' },
        { event: 'status:shipped', at: '2026-05-10T09:00:00Z' },
        { event: 'status:ready_to_ship', at: '2026-05-05T11:00:00Z' },
        { event: 'status:in_progress', at: '2026-04-28T08:00:00Z' },
        { event: 'payment_confirmed', at: '2026-04-26T10:15:00Z' },
        { event: 'proforma_issued', at: '2026-04-25T14:00:00Z' },
        { event: 'status:confirmed', at: '2026-04-24T09:30:00Z' },
        { event: 'rfq_submitted', at: '2026-04-22T12:00:00Z' },
      ],
    },
    supplier: { business_name: 'Eko Botanicals Ltd', country: 'Nigeria' },
    buyer: { business_name: 'Herbal Direct SARL', country: 'France' },
  },
};

//Listings

export const mockListings: Listing[] = [
  {
    id: 'lst-001',
    title: 'Hand-Dyed Adire Fabric Set (3 yards)',
    category: 'fashion',
    description:
      'Authentic hand-dyed Adire fabric from Abeokuta artisans. Ships from Lagos via Riby US fulfillment.',
    retail_price_usd: 65,
    stock_qty: 40,
    fulfillment_mode: 'riby_dtc',
    ships_from: 'Lagos → Riby US fulfillment',
    photos: [
      'https://images.unsplash.com/photo-1528459105426-b9548367069b?w=400&auto=format&fit=crop',
    ],
    status: 'active',
  },
  {
    id: 'lst-002',
    title: 'Organic Shea Butter (500g jar)',
    category: 'general-goods',
    description:
      'Cold-pressed unrefined shea butter from Northern Nigeria. US-stocked for 48-hour delivery.',
    retail_price_usd: 28,
    stock_qty: 120,
    fulfillment_mode: 'buyer_local',
    ships_from: 'Brooklyn, NY',
    photos: [
      'https://images.unsplash.com/photo-1590086782792-42dd2350140d?w=400&auto=format&fit=crop',
    ],
    status: 'active',
  },
  {
    id: 'lst-003',
    title: 'Premium Hibiscus Tea (250g export pack)',
    category: 'agriculture',
    description:
      'Sun-dried hibiscus petals packaged for US retail. DTC via Riby from Lagos.',
    retail_price_usd: 18,
    stock_qty: 0,
    fulfillment_mode: 'riby_dtc',
    ships_from: 'Lagos → Riby US fulfillment',
    photos: [
      'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=400&auto=format&fit=crop',
    ],
    status: 'out_of_stock',
  },
  {
    id: 'lst-004',
    title: 'Handcrafted Leather Tote — Lagos Edition',
    category: 'fashion',
    description:
      'Full-grain Nigerian leather tote, hand-stitched in Lagos. Individually numbered with origin cert.',
    retail_price_usd: 120,
    stock_qty: 15,
    fulfillment_mode: 'riby_dtc',
    ships_from: 'Lagos → Riby US fulfillment',
    photos: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&auto=format&fit=crop',
    ],
    status: 'active',
  },
  {
    id: 'lst-005',
    title: 'Moringa Powder (200g — USDA Organic)',
    category: 'general-goods',
    description:
      'USDA Organic certified moringa powder, US warehouse stocked for next-day dispatch.',
    retail_price_usd: 34,
    stock_qty: 80,
    fulfillment_mode: 'buyer_local',
    ships_from: 'Atlanta, GA',
    photos: [
      'https://images.unsplash.com/photo-1515023115689-589c33041d3c?w=400&auto=format&fit=crop',
    ],
    status: 'active',
  },
];

export const mockSellerQuotes: SellerQuote[] = [
  {
    id: 'qt-001',
    quote_number: 'QT-0041',
    listing_title: 'Hand-Dyed Adire Fabric Set (3 yards)',
    quantity: 5,
    consumer_name: 'Sarah Mitchell',
    consumer_email: 'sarah.m@gmail.com',
    message:
      'Can you do a bulk discount for 5 sets? Looking for wedding decor.',
    status: 'pending',
  },
  {
    id: 'qt-002',
    quote_number: 'QT-0038',
    listing_title: 'Organic Shea Butter (500g jar)',
    quantity: 12,
    consumer_name: 'James Okafor',
    consumer_email: 'j.okafor@yahoo.com',
    message: 'Monthly subscription possible?',
    quoted_unit_price_usd: 24,
    quoted_total_usd: 288,
    quote_valid_until: '2026-06-10',
    status: 'quoted',
  },
  {
    id: 'qt-003',
    quote_number: 'QT-0035',
    listing_title: 'Premium Hibiscus Tea (250g export pack)',
    quantity: 20,
    consumer_name: 'Amara Williams',
    consumer_email: 'amara.w@outlook.com',
    status: 'pending',
  },
];

export const mockFulfillmentOrders: FulfillmentOrder[] = [
  {
    id: 'ffo-001',
    order_number: 'SHP-0091',
    listing_title: 'Handcrafted Leather Tote — Lagos Edition',
    quantity: 2,
    unit_price_usd: 120,
    total_usd: 240,
    checkout_mode: 'listed',
    delivery_partner_of_record: 'Riby Inc',
    status: 'paid',
    escrow_status: 'held',
    created_at: '2026-05-10T09:22:00Z',
    shipping_name: 'Patricia Osei',
    shipping_address: '44 Harlem Ave, New York, NY 10037',
    shipping_email: 'p.osei@gmail.com',
    shipping_phone: '+1 646 555 0182',
  },
  {
    id: 'ffo-002',
    order_number: 'SHP-0088',
    listing_title: 'Organic Shea Butter (500g jar)',
    quantity: 12,
    unit_price_usd: 24,
    total_usd: 288,
    checkout_mode: 'quote_prepay',
    status: 'shipped',
    escrow_status: 'held',
    created_at: '2026-05-08T14:05:00Z',
    shipping_name: 'James Okafor',
    shipping_address: '12 Maple Street, Atlanta, GA 30301',
    shipping_email: 'j.okafor@yahoo.com',
    tracking_number: 'UPS-1Z999AA10123456784',
  },
  {
    id: 'ffo-003',
    order_number: 'SHP-0081',
    listing_title: 'Moringa Powder (200g — USDA Organic)',
    quantity: 4,
    unit_price_usd: 34,
    total_usd: 136,
    checkout_mode: 'listed',
    delivery_partner_of_record: 'Riby Inc',
    status: 'delivered',
    escrow_status: 'released',
    created_at: '2026-04-28T11:30:00Z',
    shipping_name: 'Chinonso Eze',
    shipping_address: '7 Oak Drive, Houston, TX 77001',
    shipping_email: 'c.eze@hotmail.com',
    shipping_phone: '+1 713 555 0244',
    tracking_number: 'FEDEX-276847211310',
  },
];

// Withdrawal Accounts Mock Data
export const mockWithdrawalAccounts: WithdrawalAccount[] = [
  {
    id: 'wa-001',
    label: 'Chase Business · Primary',
    currency: 'USD',
    bank_name: 'JPMorgan Chase',
    account_number_masked: '••••••4821',
    account_name: 'Callistus Exports Ltd',
    account_type: 'checking',
    routing_number: '021000021',
    swift_code: 'CHASUS33',
    is_default: true,
    approval_status: 'approved',
  },
  {
    id: 'wa-002',
    label: 'Bank of America · Backup',
    currency: 'USD',
    bank_name: 'Bank of America',
    account_number_masked: '••••••9134',
    account_name: 'Callistus Exports Ltd',
    account_type: 'checking',
    routing_number: '026009593',
    is_default: false,
    approval_status: 'approved',
  },
  {
    id: 'wa-003',
    label: 'GTBank Lagos · Operations',
    currency: 'NGN',
    bank_name: 'Guaranty Trust Bank',
    account_number_masked: '••••••7723',
    account_name: 'Callistus Nwosu',
    is_default: true,
    approval_status: 'approved',
  },
  {
    id: 'wa-004',
    label: 'Zenith Bank · Savings',
    currency: 'NGN',
    bank_name: 'Zenith Bank Plc',
    account_number_masked: '••••••3341',
    account_name: 'Callistus Nwosu',
    is_default: false,
    approval_status: 'pending',
  },
];

export const mockNgnBanks: NgnBank[] = [
  { code: '044', name: 'Access Bank' },
  { code: '050', name: 'EcoBank Nigeria' },
  { code: '070', name: 'Fidelity Bank' },
  { code: '011', name: 'First Bank of Nigeria' },
  { code: '214', name: 'First City Monument Bank' },
  { code: '058', name: 'Guaranty Trust Bank' },
  { code: '030', name: 'Heritage Bank' },
  { code: '301', name: 'Jaiz Bank' },
  { code: '082', name: 'Keystone Bank' },
  { code: '076', name: 'Polaris Bank' },
  { code: '221', name: 'Stanbic IBTC Bank' },
  { code: '068', name: 'Standard Chartered Bank' },
  { code: '232', name: 'Sterling Bank' },
  { code: '032', name: 'Union Bank of Nigeria' },
  { code: '033', name: 'United Bank for Africa' },
  { code: '215', name: 'Unity Bank' },
  { code: '035', name: 'Wema Bank' },
  { code: '057', name: 'Zenith Bank' },
];

// Credit Mock Data
export const mockCreditEligibility: CreditEligibility = {
  eligible: true,
  max_limit_usd: 25000,
  indicative_apr_percent: 14.5,
  indicative_term_months: 6,
  risk_score: 78,
  compliance_score: 82,
  sales: {
    paid_order_count: 12,
    total_volume_usd: 48500,
    average_order_usd: 4041.67,
  },
};

export const mockCreditApplications: CreditApplication[] = [
  {
    id: 'cred-001',
    application_number: 'JMPST-0041',
    amount_usd: 10000,
    offered_amount_usd: 9500,
    term_months: 6,
    offered_term_months: 6,
    indicative_apr: 14.5,
    offered_apr: 15.2,
    status: 'offered',
    created_at: '2026-04-10T09:00:00Z',
  },
  {
    id: 'cred-002',
    application_number: 'JMPST-0033',
    amount_usd: 5000,
    term_months: 3,
    indicative_apr: 14.5,
    status: 'approved',
    created_at: '2026-02-18T11:30:00Z',
  },
  {
    id: 'cred-003',
    application_number: 'JMPST-0021',
    amount_usd: 15000,
    term_months: 12,
    indicative_apr: 14.5,
    status: 'rejected',
    created_at: '2025-12-05T08:45:00Z',
  },
];

// Repayment Mock Data
export const mockRepaymentData: RepaymentData = {
  total_outstanding_usd: 13750,
  applications: [
    {
      application: {
        id: 'cred-001',
        application_number: 'JMPST-0041',
        offered_amount_usd: 9500,
        offered_term_months: 6,
        offered_apr: 15.2,
      },
      outstanding_usd: 6450,
      next_due: {
        due_date: '2026-06-01',
        total_due_usd: 1625,
        paid_usd: 0,
      },
      installments: [
        {
          id: 'inst-001-1',
          installment_number: 1,
          due_date: '2026-03-01',
          principal_usd: 1500,
          interest_usd: 120.42,
          total_due_usd: 1620.42,
          paid_usd: 1620.42,
          status: 'paid',
        },
        {
          id: 'inst-001-2',
          installment_number: 2,
          due_date: '2026-04-01',
          principal_usd: 1500,
          interest_usd: 101.08,
          total_due_usd: 1601.08,
          paid_usd: 1601.08,
          status: 'paid',
        },
        {
          id: 'inst-001-3',
          installment_number: 3,
          due_date: '2026-05-01',
          principal_usd: 1500,
          interest_usd: 81.75,
          total_due_usd: 1581.75,
          paid_usd: 1581.75,
          status: 'paid',
        },
        {
          id: 'inst-001-4',
          installment_number: 4,
          due_date: '2026-06-01',
          principal_usd: 1500,
          interest_usd: 62.42,
          total_due_usd: 1562.42,
          paid_usd: 0,
          status: 'pending',
        },
        {
          id: 'inst-001-5',
          installment_number: 5,
          due_date: '2026-07-01',
          principal_usd: 1500,
          interest_usd: 43.08,
          total_due_usd: 1543.08,
          paid_usd: 0,
          status: 'upcoming',
        },
        {
          id: 'inst-001-6',
          installment_number: 6,
          due_date: '2026-08-01',
          principal_usd: 1500,
          interest_usd: 23.75,
          total_due_usd: 1523.75,
          paid_usd: 0,
          status: 'upcoming',
        },
      ],
    },
    {
      application: {
        id: 'cred-002',
        application_number: 'JMPST-0033',
        offered_amount_usd: 5000,
        offered_term_months: 3,
        offered_apr: 14.5,
      },
      outstanding_usd: 7300,
      next_due: {
        due_date: '2026-06-15',
        total_due_usd: 1700,
        paid_usd: 200,
      },
      installments: [
        {
          id: 'inst-002-1',
          installment_number: 1,
          due_date: '2026-04-15',
          principal_usd: 1600,
          interest_usd: 60.42,
          total_due_usd: 1660.42,
          paid_usd: 1660.42,
          status: 'paid',
        },
        {
          id: 'inst-002-2',
          installment_number: 2,
          due_date: '2026-05-15',
          principal_usd: 1700,
          interest_usd: 40.29,
          total_due_usd: 1740.29,
          paid_usd: 900,
          status: 'overdue',
        },
        {
          id: 'inst-002-3',
          installment_number: 3,
          due_date: '2026-06-15',
          principal_usd: 1700,
          interest_usd: 20.14,
          total_due_usd: 1720.14,
          paid_usd: 0,
          status: 'upcoming',
        },
      ],
    },
  ],
};

// Onboarding Mock Data

// Uncomment to simulate a returning user mid-onboarding:
// export const mockBusiness: Business = {
//   id: 'biz-001',
//   business_name: 'Callistus Exports Ltd',
//   registration_type: 'business',
//   country: 'Nigeria',
//   sector: 'agriculture',
//   contact_phone: '+2348012345678',
//   contact_email: 'callistus@exports.ng',
//   address: '14 Apapa Industrial Estate, Lagos',
//   anchor_customer_id: 'ANC-BIZ-00124',
//   kyc_status: 'pending',
//   kyb_status: 'under_review',
//   cac_number: 'RC-1234567',
//   tin: '12345678-0001',
//   director_name: 'Callistus Nwosu',
// };

// Uncomment to simulate a fully approved business:
export const mockBusiness: Business = {
  id: 'biz-001',
  business_name: 'Callistus Exports Ltd',
  registration_type: 'business',
  country: 'Nigeria',
  sector: 'agriculture',
  contact_phone: '+2348012345678',
  contact_email: 'callistus@exports.ng',
  address: '14 Apapa Industrial Estate, Lagos',
  anchor_customer_id: 'ANC-BIZ-00124',
  anchor_ngn_virtual_account: '0123456789',
  anchor_usd_virtual_account: '9900012345',
  kyc_status: 'pending',
  kyb_status: 'pending',
  cac_number: 'RC-1234567',
  tin: '12345678-0001',
  director_name: 'Callistus Nwosu',
};
