import type { OrdersData } from './types';

export const MOCK_ORDERS: OrdersData = {
  counts: { all: 8, in_transit: 3, delivered: 4, processing: 0 },
  totals: {
    all: 1245.75,
    in_transit: 393.49,
    delivered: 722.26,
    processing: 129.0,
  },
  orders: [
    {
      id: 'ord_001',
      order_number: 'JMP-2026-0781',
      product_name: 'Handwoven Aso Oke Fabric Bundle',
      listing_title: 'Handwoven Aso Oke Fabric Bundle',
      status: 'at_customs',
      total_usd: 189.99,
      subtotal_usd: 160.0,
      unit_price_usd: 80.0,
      shipping_usd: 25.99,
      platform_fee_usd: 4.0,
      quantity: 2,
      created_at: '2026-06-20T10:30:00Z',
      tracking_number: 'DHL-9821-4567',
      delivery_partner_of_record: 'Riby Inc',
      listing_photos: ['https://picsum.photos/seed/aso-oke/200/200'],
      journey: [
        { label: 'Order placed', completed: true, date: 'Jun 20' },
        { label: 'Packed', completed: true, date: 'Jun 22' },
        { label: 'Shipped', completed: true, date: 'Jun 25' },
        { label: 'At customs', completed: true, date: 'Jul 2' },
        { label: 'Out for delivery', completed: false },
      ],
    },
    {
      id: 'ord_002',
      order_number: 'JMP-2026-0829',
      product_name: 'Premium Shea Butter Gift Set (3-Pack)',
      listing_title: 'Premium Shea Butter Gift Set',
      status: 'shipped',
      total_usd: 74.5,
      subtotal_usd: 60.0,
      unit_price_usd: 20.0,
      shipping_usd: 12.5,
      platform_fee_usd: 2.0,
      quantity: 3,
      created_at: '2026-06-28T14:15:00Z',
      tracking_number: 'DHL-7734-8821',
      delivery_partner_of_record: 'Riby Inc',
      listing_photos: ['https://picsum.photos/seed/shea-butter/200/200'],
      journey: [
        { label: 'Order placed', completed: true, date: 'Jun 28' },
        { label: 'Packed', completed: true, date: 'Jun 29' },
        { label: 'Shipped', completed: true, date: 'Jul 1' },
        { label: 'At customs', completed: false },
        { label: 'Out for delivery', completed: false },
      ],
    },
    {
      id: 'ord_003',
      order_number: 'JMP-2026-0912',
      product_name: 'Leather Laptop Sleeve – Brown',
      listing_title: 'Leather Laptop Sleeve',
      status: 'delivered',
      total_usd: 129.0,
      subtotal_usd: 115.0,
      unit_price_usd: 115.0,
      shipping_usd: 11.0,
      platform_fee_usd: 3.0,
      quantity: 1,
      created_at: '2026-07-03T08:45:00Z',
      delivery_partner_of_record: 'Riby Inc',
      listing_photos: ['https://picsum.photos/seed/leather-sleeve/200/200'],
      journey: [
        { label: 'Order placed', completed: true, date: 'Jul 3' },
        { label: 'Packed', completed: false },
        { label: 'Shipped', completed: false },
        { label: 'At customs', completed: false },
        { label: 'Out for delivery', completed: false },
      ],
    },
    {
      id: 'ord_004',
      order_number: 'JMP-2026-0654',
      product_name: 'Hand-Carved Ebony Wood Serving Bowl',
      listing_title: 'Ebony Wood Serving Bowl',
      status: 'delivered',
      total_usd: 189.5,
      subtotal_usd: 165.0,
      unit_price_usd: 165.0,
      shipping_usd: 20.0,
      platform_fee_usd: 4.5,
      quantity: 1,
      created_at: '2026-05-15T09:20:00Z',
      delivered_at: '2026-06-02T16:45:00Z',
      tracking_number: 'DHL-4410-9932',
      delivery_partner_of_record: 'Riby Inc',
      listing_photos: ['https://picsum.photos/seed/ebony-bowl/200/200'],
      journey: [
        { label: 'Order placed', completed: true, date: 'May 15' },
        { label: 'Packed', completed: true, date: 'May 17' },
        { label: 'Shipped', completed: true, date: 'May 20' },
        { label: 'At customs', completed: true, date: 'May 28' },
        { label: 'Delivered', completed: true, date: 'Jun 2' },
      ],
    },
    {
      id: 'ord_005',
      order_number: 'JMP-2026-0588',
      product_name: 'Nigerian Spice Rub Collection (4 Jars)',
      listing_title: 'Spice Rub Collection',
      status: 'delivered',
      total_usd: 69.99,
      subtotal_usd: 55.0,
      unit_price_usd: 13.75,
      shipping_usd: 12.99,
      platform_fee_usd: 2.0,
      quantity: 4,
      created_at: '2026-04-28T11:00:00Z',
      delivered_at: '2026-05-18T10:30:00Z',
      tracking_number: 'DHL-2291-7741',
      delivery_partner_of_record: 'Riby Inc',
      listing_photos: ['https://picsum.photos/seed/spice-rub/200/200'],
      journey: [
        { label: 'Order placed', completed: true, date: 'Apr 28' },
        { label: 'Packed', completed: true, date: 'Apr 30' },
        { label: 'Shipped', completed: true, date: 'May 3' },
        { label: 'At customs', completed: true, date: 'May 10' },
        { label: 'Delivered', completed: true, date: 'May 18' },
      ],
    },
    {
      id: 'ord_006',
      order_number: 'JMP-2026-0710',
      product_name: 'Cotton Kaftan – Navy Blue, XL',
      listing_title: 'Cotton Kaftan – Navy Blue',
      status: 'delivered',
      total_usd: 110.0,
      subtotal_usd: 95.0,
      unit_price_usd: 95.0,
      shipping_usd: 13.0,
      platform_fee_usd: 2.0,
      quantity: 1,
      created_at: '2026-06-05T15:30:00Z',
      delivered_at: '2026-06-25T09:15:00Z',
      delivery_partner_of_record: 'Riby Inc',
      listing_photos: ['https://picsum.photos/seed/kaftan/200/200'],
      journey: [
        { label: 'Order placed', completed: true, date: 'Jun 5' },
        { label: 'Packed', completed: true, date: 'Jun 7' },
        { label: 'Shipped', completed: true, date: 'Jun 10' },
        { label: 'At customs', completed: true, date: 'Jun 17' },
        { label: 'Delivered', completed: true, date: 'Jun 25' },
      ],
    },
    {
      id: 'ord_007',
      order_number: 'JMP-2026-0881',
      product_name: 'Beaded Leather Sandals – Size 9',
      listing_title: 'Beaded Leather Sandals',
      status: 'delivered',
      total_usd: 352.77,
      subtotal_usd: 310.0,
      unit_price_usd: 62.0,
      shipping_usd: 35.77,
      platform_fee_usd: 7.0,
      quantity: 5,
      created_at: '2026-06-12T13:00:00Z',
      delivered_at: '2026-07-01T14:20:00Z',
      delivery_partner_of_record: 'Riby Inc',
      listing_photos: ['https://picsum.photos/seed/sandals/200/200'],
      journey: [
        { label: 'Order placed', completed: true, date: 'Jun 12' },
        { label: 'Packed', completed: true, date: 'Jun 14' },
        { label: 'Shipped', completed: true, date: 'Jun 17' },
        { label: 'At customs', completed: true, date: 'Jun 25' },
        { label: 'Delivered', completed: true, date: 'Jul 1' },
      ],
    },
    {
      id: 'ord_008',
      order_number: 'JMP-2026-0930',
      product_name: 'Organic Hibiscus Dried Flowers – 200g',
      listing_title: 'Organic Hibiscus Dried Flowers',
      status: 'shipped',
      total_usd: 129.0,
      subtotal_usd: 113.96,
      unit_price_usd: 18.99,
      shipping_usd: 12.99,
      platform_fee_usd: 2.05,
      quantity: 6,
      created_at: '2026-07-04T09:45:00Z',
      tracking_number: 'DHL-5589-1123',
      delivery_partner_of_record: 'Riby Inc',
      listing_photos: ['https://picsum.photos/seed/hibiscus/200/200'],
      journey: [
        { label: 'Order placed', completed: true, date: 'Jul 4' },
        { label: 'Packed', completed: true, date: 'Jul 5' },
        { label: 'Shipped', completed: false },
        { label: 'At customs', completed: false },
        { label: 'Out for delivery', completed: false },
      ],
    },
  ],
};

export const FILTERS = [
  { v: 'all' as const, l: 'All' },
  { v: 'in_transit' as const, l: 'In Transit' },
  { v: 'delivered' as const, l: 'Delivered' },
  { v: 'processing' as const, l: 'Processing' },
];

export function categoryOf(
  status: string,
): 'in_transit' | 'delivered' | 'processing' | 'other' {
  const s = status.toLowerCase();
  if (['shipped', 'in_transit', 'at_customs', 'customs'].includes(s))
    return 'in_transit';
  if (['delivered', 'released'].includes(s)) return 'delivered';
  if (
    [
      'pending',
      'created',
      'paid',
      'processing',
      'packed',
      'confirmed',
    ].includes(s)
  )
    return 'processing';
  return 'other';
}
