import type { Address } from './types';

export const MOCK_ADDRESSES: Address[] = [
  {
    id: 1,
    label: 'Home',
    recipientName: 'Chioma Okonkwo',
    addressLine1: '451 Maple Ave',
    addressLine2: 'Apt 3B',
    city: 'Houston',
    state: 'TX',
    postalCode: '77002',
    phoneNumber: '+1 202 555 0147',
    isDefault: true,
  },
  {
    id: 2,
    label: 'Office',
    recipientName: 'Chioma Okonkwo',
    addressLine1: '2800 Post Oak Blvd',
    addressLine2: '',
    city: 'Houston',
    state: 'TX',
    postalCode: '77056',
    phoneNumber: '',
    isDefault: false,
  },
  {
    id: 3,
    label: "Sister's Place",
    recipientName: 'Nneka Okonkwo',
    addressLine1: '1420 Washington Ave',
    addressLine2: 'Unit 7',
    city: 'Miami',
    state: 'FL',
    postalCode: '33139',
    phoneNumber: '+1 305 555 0234',
    isDefault: false,
  },
];
